class GameLevelDesign {
  const GameLevelDesign({
    required this.levelIndex,
    required this.stage,
    required this.wave,
    required this.difficulty,
    required this.objective,
    required this.goldReward,
    required this.xpReward,
    required this.progressionUnlock,
  });

  final int levelIndex;
  final String stage;
  final int wave;
  final double difficulty;
  final String objective;
  final int goldReward;
  final int xpReward;
  final String progressionUnlock;
}

const kGameTitle = 'Kingdom Rebuild Project';
const kCoreFunLoop = 'Build, Upgrade and Grow';

const kCoreLoopPillars = <String>[
  'Start',
  'Act',
  'React',
  'Reward',
  'Upgrade',
  'Return',
];

const kLevelTensionBeats = <String>[
  'basic_hut',
  'small_farm',
  'basic_mine',
  'small_workshop',
  'basic_storehouse',
  'village_hall',
  'farm_terrace',
  'mine_works',
  'castle_foundation',
  'market_square',
  'grand_gate',
  'castle_keep',
  'palace_wing',
  'monument_plaza',
  'castle_harbor',
  'palace_garden',
  'grand_aqueduct',
  'monument_watchtower',
  'castle_barracks',
  'kingdom_treasury',
  'grand_cathedral',
  'palace_armory',
  'monument_bridge',
  'castle_archive',
  'grand_citadel',
  'palace_observatory',
  'grand_harbor',
  'monument_crown_hall',
  'castle_throne',
  'kingdom_reborn',
];

const kDefaultBalancingConfig = <String, Object>{
  'difficultyCurve': 'thirty_step_kingdom_rebuild',
  'targetSessionSeconds': 210,
  'rewardCadence': 'every_level_with_boss_bonus',
  'progressionReset': 'repeatable_loop',
  'failureRecovery': 'keep_progress_retry_level',
};

const kMetaProgressionSystems = <String>[
  'DailyQuest',
  'Achievement',
  'BattlePass',
  'Gacha',
  'Collection',
  'Progression',
];

const kLevelDesign = <GameLevelDesign>[
  GameLevelDesign(
    levelIndex: 1,
    stage: 'Basic Village Hut',
    wave: 1,
    difficulty: 1.00,
    objective: 'Rebuild the kingdom: Raise the first safe shelter',
    goldReward: 50,
    xpReward: 20,
    progressionUnlock: 'tutorial complete',
  ),
  GameLevelDesign(
    levelIndex: 2,
    stage: 'Small Farm Build',
    wave: 2,
    difficulty: 1.12,
    objective: 'Rebuild the kingdom: Plant the first food route',
    goldReward: 80,
    xpReward: 35,
    progressionUnlock: 'daily quest',
  ),
  GameLevelDesign(
    levelIndex: 3,
    stage: 'Basic Mine Shack',
    wave: 3,
    difficulty: 1.28,
    objective: 'Rebuild the kingdom: Reopen a stone supply point',
    goldReward: 120,
    xpReward: 54,
    progressionUnlock: 'upgrade option',
  ),
  GameLevelDesign(
    levelIndex: 4,
    stage: 'Small Builder Workshop',
    wave: 4,
    difficulty: 1.50,
    objective: 'Rebuild the kingdom: Train builders for faster repairs',
    goldReward: 170,
    xpReward: 78,
    progressionUnlock: 'booster',
  ),
  GameLevelDesign(
    levelIndex: 5,
    stage: 'Basic Village Storehouse',
    wave: 5,
    difficulty: 1.76,
    objective: 'Rebuild the kingdom: Secure resources against raids',
    goldReward: 235,
    xpReward: 108,
    progressionUnlock: 'collection slot',
  ),
  GameLevelDesign(
    levelIndex: 6,
    stage: 'Restore Village Hall',
    wave: 6,
    difficulty: 2.05,
    objective: 'Rebuild the kingdom: Reopen town decisions and worker planning',
    goldReward: 315,
    xpReward: 144,
    progressionUnlock: 'rank promotion',
  ),
  GameLevelDesign(
    levelIndex: 7,
    stage: 'Construct Farm Terrace',
    wave: 7,
    difficulty: 2.38,
    objective: 'Rebuild the kingdom: Expand food production up the ridge',
    goldReward: 410,
    xpReward: 188,
    progressionUnlock: 'tournament ticket',
  ),
  GameLevelDesign(
    levelIndex: 8,
    stage: 'Kingdom Mine Works',
    wave: 8,
    difficulty: 2.75,
    objective: 'Rebuild the kingdom: Chain mine output into construction flow',
    goldReward: 525,
    xpReward: 240,
    progressionUnlock: 'season score',
  ),
  GameLevelDesign(
    levelIndex: 9,
    stage: 'Castle Wall Foundation',
    wave: 9,
    difficulty: 3.16,
    objective: 'Rebuild the kingdom: Lay the first defensive ring',
    goldReward: 660,
    xpReward: 300,
    progressionUnlock: 'wall blueprint',
  ),
  GameLevelDesign(
    levelIndex: 10,
    stage: 'Restore Market Square',
    wave: 10,
    difficulty: 3.61,
    objective: 'Rebuild the kingdom: Bring trade back to the central plaza',
    goldReward: 815,
    xpReward: 368,
    progressionUnlock: 'merchant charter',
  ),
  GameLevelDesign(
    levelIndex: 11,
    stage: 'Grand Castle Gate',
    wave: 11,
    difficulty: 4.10,
    objective:
        'Rebuild the kingdom: Fortify the main gate before pressure peaks',
    goldReward: 990,
    xpReward: 444,
    progressionUnlock: 'gatehouse',
  ),
  GameLevelDesign(
    levelIndex: 12,
    stage: 'Castle Keep Restoration',
    wave: 12,
    difficulty: 4.63,
    objective: 'Rebuild the kingdom: Restore command rooms inside the keep',
    goldReward: 1185,
    xpReward: 528,
    progressionUnlock: 'keep council',
  ),
  GameLevelDesign(
    levelIndex: 13,
    stage: 'Grand Palace Wing',
    wave: 13,
    difficulty: 5.20,
    objective: 'Rebuild the kingdom: Repair noble quarters for diplomacy',
    goldReward: 1400,
    xpReward: 620,
    progressionUnlock: 'diplomacy hall',
  ),
  GameLevelDesign(
    levelIndex: 14,
    stage: 'Kingdom Monument Plaza',
    wave: 14,
    difficulty: 5.81,
    objective: 'Rebuild the kingdom: Restore morale with a central monument',
    goldReward: 1635,
    xpReward: 720,
    progressionUnlock: 'morale bonus',
  ),
  GameLevelDesign(
    levelIndex: 15,
    stage: 'Castle Harbor',
    wave: 15,
    difficulty: 6.46,
    objective: 'Rebuild the kingdom: Reconnect river supply lines',
    goldReward: 1890,
    xpReward: 828,
    progressionUnlock: 'harbor trade',
  ),
  GameLevelDesign(
    levelIndex: 16,
    stage: 'Palace Garden Build',
    wave: 16,
    difficulty: 7.15,
    objective:
        'Rebuild the kingdom: Balance beauty, food, and citizen happiness',
    goldReward: 2165,
    xpReward: 944,
    progressionUnlock: 'garden festival',
  ),
  GameLevelDesign(
    levelIndex: 17,
    stage: 'Grand Aqueduct',
    wave: 17,
    difficulty: 7.88,
    objective: 'Rebuild the kingdom: Bring clean water across the capital',
    goldReward: 2460,
    xpReward: 1068,
    progressionUnlock: 'waterworks',
  ),
  GameLevelDesign(
    levelIndex: 18,
    stage: 'Monument Watchtower',
    wave: 18,
    difficulty: 8.65,
    objective: 'Rebuild the kingdom: Guard the borders and spot raids early',
    goldReward: 2775,
    xpReward: 1200,
    progressionUnlock: 'watch patrol',
  ),
  GameLevelDesign(
    levelIndex: 19,
    stage: 'Castle Barracks',
    wave: 19,
    difficulty: 9.46,
    objective: 'Rebuild the kingdom: Train defenders for the next expansion',
    goldReward: 3110,
    xpReward: 1340,
    progressionUnlock: 'guard roster',
  ),
  GameLevelDesign(
    levelIndex: 20,
    stage: 'Kingdom Treasury',
    wave: 20,
    difficulty: 10.31,
    objective: 'Rebuild the kingdom: Protect long-term wealth and taxes',
    goldReward: 3465,
    xpReward: 1488,
    progressionUnlock: 'tax ledger',
  ),
  GameLevelDesign(
    levelIndex: 21,
    stage: 'Grand Cathedral Build',
    wave: 21,
    difficulty: 11.20,
    objective: 'Rebuild the kingdom: Complete a landmark for citizen loyalty',
    goldReward: 3840,
    xpReward: 1644,
    progressionUnlock: 'loyalty rite',
  ),
  GameLevelDesign(
    levelIndex: 22,
    stage: 'Palace Armory',
    wave: 22,
    difficulty: 12.13,
    objective: 'Rebuild the kingdom: Equip elite builders and guards',
    goldReward: 4235,
    xpReward: 1808,
    progressionUnlock: 'elite gear',
  ),
  GameLevelDesign(
    levelIndex: 23,
    stage: 'Monument Bridge',
    wave: 23,
    difficulty: 13.10,
    objective: 'Rebuild the kingdom: Connect outer villages to the capital',
    goldReward: 4650,
    xpReward: 1980,
    progressionUnlock: 'bridge tolls',
  ),
  GameLevelDesign(
    levelIndex: 24,
    stage: 'Castle Archive',
    wave: 24,
    difficulty: 14.11,
    objective: 'Rebuild the kingdom: Recover blueprints for ancient structures',
    goldReward: 5085,
    xpReward: 2160,
    progressionUnlock: 'ancient plans',
  ),
  GameLevelDesign(
    levelIndex: 25,
    stage: 'Grand Citadel',
    wave: 25,
    difficulty: 15.16,
    objective: 'Rebuild the kingdom: Finish the strongest defensive tier',
    goldReward: 5540,
    xpReward: 2348,
    progressionUnlock: 'citadel guard',
  ),
  GameLevelDesign(
    levelIndex: 26,
    stage: 'Palace Observatory',
    wave: 26,
    difficulty: 16.25,
    objective: 'Rebuild the kingdom: Forecast threats and prosperity windows',
    goldReward: 6015,
    xpReward: 2544,
    progressionUnlock: 'royal astronomy',
  ),
  GameLevelDesign(
    levelIndex: 27,
    stage: 'Kingdom Grand Harbor',
    wave: 27,
    difficulty: 17.38,
    objective: 'Rebuild the kingdom: Open overseas trade and migration',
    goldReward: 6510,
    xpReward: 2748,
    progressionUnlock: 'fleet charter',
  ),
  GameLevelDesign(
    levelIndex: 28,
    stage: 'Monument Crown Hall',
    wave: 28,
    difficulty: 18.55,
    objective: 'Rebuild the kingdom: Host the first full council ceremony',
    goldReward: 7025,
    xpReward: 2960,
    progressionUnlock: 'crown council',
  ),
  GameLevelDesign(
    levelIndex: 29,
    stage: 'Castle Throne Restoration',
    wave: 29,
    difficulty: 19.76,
    objective:
        'Rebuild the kingdom: Restore the throne and final civic systems',
    goldReward: 7560,
    xpReward: 3180,
    progressionUnlock: 'throne restored',
  ),
  GameLevelDesign(
    levelIndex: 30,
    stage: 'Grand Kingdom Reborn',
    wave: 30,
    difficulty: 21.01,
    objective:
        'Rebuild the kingdom: Complete the capital and unlock repeatable prestige',
    goldReward: 8115,
    xpReward: 3408,
    progressionUnlock: 'kingdom reborn',
  ),
];
